### ISSUE TITLE
Verify legacy API compatibility

### ISSUE THREAD

**Issue by becominginsane** [Zondax/ledger-tezos#131]
Currently we provide the legacy API but there are only limited checks done to verify that this API is actually compatible with the one from the legacy app

**Comment by becominginsane** [comment]
As part of #173, a default watermark is being returned even when there's no watermark written in the first place.
Unable to test and verify with the legacy baking app, a value of "0" was chosen as default.

It would be ideal if we can check with the legacy app what value is returned, or consider concerns with this default value compared to others like `u32::MAX`

**Comment by becominginsane** [comment]
Changed default HWM to `u32::MAX`

See 61b0da8e9f5d0a7c8e5df7e87672b53d5c2af68c @ rust/app/src/handlers/hwm.rs

**Comment by jleni** [comment]
I am not sure the exact purpose of this issue. 
At the moment, we have relatively a good amount of tests that use both apps.
We can use this issue to track the task of adding a few more tests for feature A, B, C.. otherwise, I would close it and add new issues as we recognize them.
