### ISSUE TITLE
Match Makefile app version with code

### ISSUE THREAD

**Issue by becominginsane** [Zondax/ledger-tezos#171]
Currently the version number is repeated twice, once in the app's Makefile and a second time in the version instruction handler.

These a risk of these 2 not being synced overtime and that could eventually cause confusion where we release a version and the app returns another.

Maybe we can do something thru a proc macro? cc @jleni

**Comment by jleni** [comment]
Look at what we do here:

The version is placed in a file like this:
https://github.com/Zondax/ledger-polkadot/blob/main/app/Makefile.version

the Makefile imports the values here:
https://github.com/Zondax/ledger-polkadot/blob/341011cadc2f9b3f3eeb0f73547ceae083b18c5d/app/Makefile#L68

and some other language like C++ (CMakefiles), can treat that file as environment variables or just read the "settings"
so in that case you could use a proc macro that reads this file

**Comment by becominginsane** [comment]
See dd6d7024d1c0cd84226cd4c876258e63ec7aae5f
