### ISSUE TITLE
smart contract call should display amount of tez

### ISSUE THREAD

**Issue by nicolasochem** [Zondax/ledger-tezos#208]
With the current C ledger app, when I execute a smart contract, I only see a large string on the ledger screen (blind signing). That makes sense, however in Tezos all smart contract execution is associated with a transfer of native currency (tez) which may optionally be zero. In my opinion, this amount should appear explicitly on screen, even when the rest of the operation is only shown as a string.

This is how blind signing in the Ethereum ledger app works, it should be the same on tez.

Example of smart contract execution in the tezos CLI:

```
tezos-client \
  --endpoint https://rpc.ghostnet.teztnets.xyz \
  transfer 1 from <YOUR BAKER ADDRESS> to <SMART CONTRACT> \
  --entrypoint 'whatever' \
  --arg '"whatever"'
  --burn-cap 0.037
```

In this case, I would like to see on the ledger screen that I am transfering 1 tez to the contract.

Note: it may already be the case in the new ledger app. I didn't try. If that's the case, feel free to close.

:link: [zboto Link](https://app.clickup.com/t/2wu6760)

**Comment by jevonearth** [comment]
The new Zondax Tezos Ledger wallet version 3.1.2 does display the transfer amount. You can see the video below that shows a contract execution.

https://youtu.be/HSBqSnnh2iw

**Comment by nicolasochem** [comment]
thank you
