### ISSUE TITLE
Mock bindings (or higher level API)

### ISSUE THREAD

**Issue by becominginsane** [Zondax/ledger-tezos#37]
Currently `feature/bindings` provides the barebones for compiling the app code when in a bolos environment.
This is okay and more ergonomic bindings will be added as features are needed.

Here's the catch:
The bindings are, of course, invalid when there's no bolos environment or emulator to run the app, rendering unit tests impossible currently.

So this is the tracking issue to provide mocking of such bindings (or the ergonomic wrappers on top) so that unit tests will be possible once again

Current ideas:
* provide a separate module in the app directly with all the mocked implementation and expose it thru the `sys` module, instead of `bolos-sys` and `zemu-sys`
* provide said module in a crate instead for better reusability (and to not track all needed dependencies in the app manifest)

**Comment by neithanmo** [comment]
what is the status of this issue, from what I have seen I think this can be closed?? @becominginsane ?

**Comment by becominginsane** [comment]
Indeed
