### ISSUE TITLE
Authorize Baking Operation

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-tezos#59]
Add support for INS_AUTHORIZE_BAKING (baking mode)

_Originally posted by @jleni in https://github.com/Zondax/ledger-tezos/issues/18#issuecomment-862558060_

**Comment by jleni** [comment]
@leongb we can close this correct?

**Comment by leongb** [comment]
There is currently support in the new style, but we still need to add legacy support + check with test vectors that this is correct.
