### ISSUE TITLE
Cache rust dependencies

### ISSUE THREAD

**Issue by becominginsane** [Zondax/ledger-tezos#91]
Currently when building the app Cargo will try to update it's index and fetch all dependencies, which can take some time (10 minutes) as the index is really big.

We could make use of a cache to reduce this step to a few seconds when `rust/Cargo.lock`'s hash hasn't changed (no dependency change). It's not common to change our dependencies so we would hit the cache fairly often.

**Comment by emmanuelm41** [comment]
@becominginsane Can you tell me where the generated files are located? I mean, the ones we should cache.

**Comment by becominginsane** [comment]
`rust/app/.cargo` is Cargo's home directory for the project and it should be caching everything there. If we are still not hitting the cache completely then we either need to change the Makefiles a bit or cache `$HOME/.cargo`  too
